### ISSUE TITLE
🖤☀️❤️ Aboriginal Flag emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#116]
Although not having a state of their own, Australian Aborigines have a flag. Torres Strait Islanders have a separate one.

**Solution**: Upon [formal request](http://www.standards.org.au/StandardsDevelopment/Developing_Standards/Documents/Proposal%20Form%20-%20Standards%20Development%20Projects.doc), [Standards Australia](http://www.standards.org.au/StandardsDevelopment/Developing_Standards/Pages/default.aspx) could add a new subdivision category for a “pseudo region”, e.g. _nation_, to AS 4590, which would likely get it also into [ISO 3166-2:AU](https://www.iso.org/obp/ui/#iso:code:3166:AU) and hence CLDR and thus Emoji Tag Sequences in UTR#51. The actual code elements could be `AU-AB` and `AU-TS`, for instance, or `AU-O` and `AU-I`. 
For reference, the [respective standard for the United Kingdom](https://www.iso.org/obp/ui/#iso:code:3166:GB), BS 6879, has categories such as _country, nation_ and _province_ besides lower-level districts.

People could also try to establish (and then [propose for inclusion](http://unicode.org/emoji/selection.html) in UTR#51) an Emoji ZWJ Sequence, e.g. 🖤&zwj;☀️&zwj;❤️ or 🖤&zwj;🌕&zwj;❤️ or ⚫️&zwj;💛&zwj;🔴 for the Aboriginal flag.

There seem to be some licensing or copyright issues regarding the flag with two horizontal stripes, black on top and red on bottom, with a superimposed filled yellow circle in the middle representing the sun.

## Petitions

- [change.org: Aboriginal Flag ![](https://assets.change.org/photos/2/we/cp/SEWECpGLFzwdKHE-800x450-noPad.jpg?1478819680)](https://www.change.org/p/apple-an-aboriginal-flag-emoji-needs-to-be-released)
- [change.org: Torres Strait Islander and Australian Aboriginal Flags](https://www.change.org/p/shigetaka-kurita-the-aboriginal-torres-strait-islander-flag-emojis)

## Press

- [Slate: Twitter's newest hashflag emoji helps promote visibility for Australian Aborigines](http://www.slate.com/blogs/future_tense/2017/05/26/twitter_s_newest_hashflag_emoji_helps_promote_visibility_for_australian.html "There Was No Emoji Flag for Australia’s Indigenous Peoples. Twitter Just Made One. by Ian Prasad Philbrick (2017-05-26)")

**Comment by Crissov** [comment]
Mockups
---------

Twemoji ![Aboriginal flag](https://cloud.githubusercontent.com/assets/6200185/24824296/05066874-1c09-11e7-8232-6facb3210fb5.png)

**Comment by spacekitteh** [comment]
Is there a petition/proposal for the Torres Strait Island flag?

**Comment by Crissov** [comment]
@spacekitteh I have not come across any yet.

**Comment by pento** [comment]
@Crissov: Are you aware of any submissions to Standards Australia related to this? I've had a look through their [recent updates](http://www.standards.org.au/StandardsDevelopment/Sectors/Pages/Sector-Updates.aspx), but nothing is jumping out.

The next project submission round starts next week, I can put some time into getting this moving, if it isn't already.

**Comment by Crissov** [comment]
No, @pento. I would have documented any such progress here.

That being said, flags not covered by ISO 3166 seem to have been discussed briefly at the last Unicode meeting a few days ago. https://twitter.com/jeremyburge/status/892153023450959872

**Comment by pento** [comment]
Thanks for the link! I'll follow up with Jeremy. 🙂

**Comment by pento** [comment]
Jeremy advised that an ISO subdivision code would be helpful: https://twitter.com/jeremyburge/status/894541514243805184

I've contacted Standards Australia to start that process.

**Comment by pento** [comment]
This was a few years ago, I forgot to update this discussion. 🙂 With [the licensing issues finally being resolved](https://www.pm.gov.au/media/free-use-aboriginal-flag-secured-all-australians), it's a good time to revisit it, however.

I managed to get in contact with some folks at Standards Australia and Geoscience Australia, unfortunately that discussion died out, but the general sense I got was that they weren't keen on the idea of adding psuedo regions to ISO 3166-2:AU. I can reach out see if I can pick up the conversation again with my original contacts, to evaluate if that might've changed.

That said, In the years since this discussion started, it seems like [🖤💛❤️ has become the _de facto_ standard](https://twitter.com/search?q=%22%F0%9F%96%A4%F0%9F%92%9B%E2%9D%A4%EF%B8%8F%22&src=typed_query&f=live) for signifying the Aboriginal flag, though there's no common equivalent for the Torres Strait Island flag. I occasionally see 💚💙 used, but it's far from ubiquitous.

Per the [emoji submission guidelines](https://unicode.org/emoji/proposals.html#Flags), however, it seems like both of these avenues would currently result in a proposal being rejected. The F3 category leaves an option open for proposing a general method for recognising flags of this nature, but I don't know if there's any work in progress on this.

@Crissov, do you have any thoughts on what the most constructive way forward might be?

**Comment by Crissov** [comment]
Since the ESC isn’t keen on adding any more flags, I don’t see any viable way at the moment. <https://unicode.org/emoji/proposals.html#Flags>

**Comment by bardiharborow** [comment]
> The F3 category leaves an option open for proposing a general method for recognising flags of this nature, but I don't know if there's any work in progress on this.

It seems to me that they are suggesting that if they were to approve something, it would need a new ISO (or similar) standard to get codes for these identities/ethnic groups/whatever the scope is here, and then a proposal for a new modifier mechanism?

**Comment by spiringwriter2** [comment]
Nice, looks GOOD            [![Image](https://github.com/user-attachments/assets/bd22ba9f-3b42-4665-9eeb-d764f0a0fe04)](https://rickycasino3.com/au)
