### ISSUE TITLE
South Vietnam flag emoji

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#353]
North and South Vietnam had separate alpha-2 codes in ISO 3166-1 prior to 1977, `VD` (Democratic Republic) and `VN` (State / Republic), respectively. Since unification, only `VN` has been assigned, although `VD` (Socialist Republic) had won the war (and hence `VDVN` is available as an ISO 3166-4 code element, but not `VNVN`). There is no Vietnamese subregion that resembles the former independent state of South Vietnam. That means, an Emoji Flag Tag Sequence is not possible as currently specified in UTS#51.

:yellow_heart::broken_heart::yellow_heart: 

![The Southern Vietnamese flag has a yellow canvas with three red horizontal stripes in the middle](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Flag_of_South_Vietnam.svg/640px-Flag_of_South_Vietnam.svg.png)

Petitions
----------

- [change.org](https://www.change.org/p/unicode-the-republic-of-vietnam-south-vietnam-flag)

Standard References
-------------------

- [Unicode Technical Standard 51 “Unicode Emoji”](http://unicode.org/reports/tr51/) ([beta](http://unicode.org/reports/tr51/proposed.html))
- [How to propose emojis to Unicode](http://unicode.org/emoji/selection.html)
- [How to propose other additions or changes to Unicode](http://www.unicode.org/pending/proposals.html) ([required form](http://www.unicode.org/L2/summary.html), email address: [docsubmit＠unicode.org](mailto:docsubmit@unicode.org?subject=UTC%20Document%20Submission:%20{name%20of%20your%20topic}&body=Please%20consider%20the%20attached%20document%20for%20submission%20to%20the%20UTC))
- [Unicode document submission form](http://www.unicode.org/reporting.html)

**Comment by Crissov** [comment]
Mockup
---------

Emojitwo: ![south vietnamese flag](https://user-images.githubusercontent.com/6200185/29005588-90828e4e-7ade-11e7-9c12-34c7ed3cd53b.png)

**Comment by Crissov** [comment]
The Emoji Subcommittee at the Unicode consortium has recently added an exclusion criterion for [Region Flags without Code](https://www.unicode.org/emoji/proposals.html#Region_Flags_Without_Code).

Since [ISO 3166-2:VN](https://www.iso.org/obp/ui#iso:code:3166:VN) does not include codes for collective regions like North and South Vietnam, this makes any proposal a non-starter.

**Comment by phodamentals** [comment]
@Crissov - Thank you for this particular unicode proposal. I understand that ISO 3166-2:VN doesn't include codes for collective regions for countries or nations, however would it be possible to make a submission under a different category and name?  Similar to how Pride flags are? The flag of former South Vietnam is recognized as the "Vietnamese Heritage and Freedom Flag" and it is widely known that this same flag represents countless Vietnamese overseas refugee communities, which fly the banner with pride. It is currently recognized by 13 U.S. state governments, seven counties and 85 cities in 20 states in the U.S. and many other communities around the world.  Would this be a better approach to possibly gain traction?  Not sure how the sequencing would look...
https://www.change.org/p/unicode-the-republic-of-vietnam-south-vietnam-flag

**Comment by Crissov** [comment]
It would be possible in theory, but I am sure it would not pass unless the selection criteria receive a significant update.

**Comment by phodamentals** [comment]
😥

💛💔💛

**Comment by baohouse** [comment]
@Crissov Small typo, you meant to say ISO 3166-3 (not ISO 3166-4). Yes, VNVN is not available. Seems one possible path is to get VNVN listed on ISO 3166-3 (to represent the former Republic of Vietnam), followed by a mechanism to encode ISO 3166-3 entities for flags. Though, this seems like a very difficult path.

We can try using zero width joiners (ZWJ) in a manner similar to the rainbow flag 🏳️‍🌈. So here are some ideas:

## Using existing country flag as a base
Combine the current Vietnamese flag emoji 🇻🇳 sequence with down-arrow ⬇️which represents "south". U+1F1FB+1F1F3+200D+2B07
🇻+🇳+[ZWJ]+⬇️

1. Pro: Does not require ISO 3361 code since it doesn't exist for South Vietnam (anymore)
2. Pro: Relates the two flags to each other, since 🇻🇳 is the official flag, and the South Vietnam flag is a former flag for the area now part of current Vietnam.
3. Con: Implies that the yellow flag is used to indicate a region, which the UTS#51 has rules concerning that flags that indicate regions must have an ISO 3361-1 code, or be encoded using tags for subdivisions. While it is true that in a historical context the flag indicated a region, its current-day usage is to refer to people, which is similar to rainbow flag 🏳️‍🌈. That could be hard to convince the committee, however, with the country flag as part of the ZWJ sequence.
4. Con: The fallback 🇻🇳⬇️ could be confusing for users communicating with each other.

## Using geometric composition
Geometric composition. U+1F3F3+FE0F+200D+1F7E8+200D+2630+200D+F7E5
🏳️+[VS16]+[ZWJ]+🟨+[ZWJ]+☰+[ZWJ]+🟥
or even simply U+1F3F3+FE0F+200D+2630
🏳️+[VS16]+[ZWJ]+☰

1. Pro: Does not require ISO 3361 code since it doesn't exist for South Vietnam (anymore)
2. Pro: Does not depend on flag of any country, and therefore does not imply a region, especially since current usage is mainly for representing people.
3. Pro: Uses a trigram. That is what the three stripes is historically based upon. The flag of South Korea is the only other flag to my knowledge that uses trigrams. The simpler variant 🏳️☰ makes fallback look cleaner.
4. Con: Does not easily suggest a relationship to the current Vietnam flag. Vendors could have to track that relationship themselves in the UI.

## How to have it display in UI

If I were to make the case to vendors who worry about UI, I believe on my iPhone I can hold down, say, the woman emoji 👩, and a pop-up would show skin tone options. Why not allow the same for flags? I don't mind the South Vietnam flag emoji to be an alternate to the current Vietnam flag 🇻🇳 using the same popup mechanism.

## References
* [Emoji Flags Explained](https://blog.emojipedia.org/emoji-flags-explained/)
* [There’s now a formal proposal for a rainbow flag emoji](https://qz.com/737351/theres-now-a-formal-proposal-for-a-rainbow-flag-emoji/)

## Using colored symbols
💛💔💛 seems like most available on various platform
🟨🩸🟨 Squares more of a flag shape, though not necessarily available on all platforms. Blood is the symbol of the stripes, but not available on all platforms either.
💛🩸💛Heart and blood makes sense together.

**Comment by phodamentals** [comment]
How can we get more traction on this? :muscle:

**Comment by anle1337** [comment]
> How can we get more traction on this? 💪

+1

**Comment by kevinhtran** [comment]
> How can we get more traction on this? 💪


+1

**Comment by phodamentals** [comment]
@baohouse thanks for the analysis and suggestions.

Obviously this is in a 'backlog' of sorts. :smile: 

@Crissov, thoughts to @baohouse's comment?

**Comment by anle1337** [comment]
great follow up @phodamentals

**Comment by Crissov** [comment]
JFTR

- 🟡🔴🟡
- 🟡⭕🟡
- 🟨🟥🟨

**Comment by anle1337** [comment]
whats jftr mean? sorry @Crissov

**Comment by phodamentals** [comment]
:skull: 

@anle1337 "Just for the record."

However...@Crissov closing this issue is likely because of:
![Screenshot from 2022-03-29 13-47-29](https://user-images.githubusercontent.com/3144570/160683750-6fdb0493-3721-45f8-bfd0-5f57b9922486.png)

Full link: https://home.unicode.org/the-past-and-future-of-flag-emoji/

**Comment by anle1337** [comment]
interesting thanks

**Comment by Crissov** [comment]
Exactly. I closed all issues for flag emojis, because Unicode won’t process them anymore.

**Comment by baohouse** [comment]
@phodamentals Welp, someone's gotta inform the petition organizer of the news.

At this point the only idea I can think of is to create proof-of-concept software.

On the rendering side, using browser extensions that replace content within a webpage with a custom image. So, assuming the 🟨🟥🟨 sequence is our convention to signify the flag as a fallback, automatically replace that sequence on any webpage with an SVG of the flag. There are already text-replacement extensions out there to draw inspiration from. This would be for situations such as GitHub/Twitter/Instagram profiles. For website developers who control their own sites, there can be some kind of JavaScript-based page-scanning text substitution library, reducing the need for the extension.

Inputting the flag is a bit more complicated. For iOS users, probably would have to build a custom keyboard extension which has the ability to enter in macros such as the 🟨🟥🟨 sequence (with the flag as the actual preview to tap on). MacBook users would probably use a custom version of the Character Viewer.
https://developer.apple.com/design/human-interface-guidelines/ios/extensions/custom-keyboards/

Once the prototype exists, one can easily generalize this for use within any community that wishes to identify themselves with their own flag.

Essentially we'd have to do the same thing as the early Unicode pioneers did in building Unicode support on top of ASCII-based systems (especially UTF-8 encoding).

**Comment by anle1337** [comment]
@baohouse cool concept that you thought of. I find it hard to believe that a large audience would be interested in a chrome extension to replace color emojis with flags.

The reason is that flag emojis are already one of the lowest usage emojis, and there would be too much friction to get users to download a chrome extension that would detect color square emojis and replace them with the appropriate SVG flag image. Combine that with the odds of someone using the color rectangle sequences in the hopes that other people have the chrome extension installed, I feel this chrome extension concept wouldn't get widespread adoption. Just my 2 cents

**Comment by baohouse** [comment]
> @baohouse cool concept that you thought of. I find it hard to believe that a large audience would be interested in a chrome extension to replace color emojis with flags.
> 
> The reason is that flag emojis are already one of the lowest usage emojis, and there would be too much friction to get users to download a chrome extension that would detect color square emojis and replace them with the appropriate SVG flag image. Combine that with the odds of someone using the color rectangle sequences in the hopes that other people have the chrome extension installed, I feel this chrome extension concept wouldn't get widespread adoption. Just my 2 cents

@anle1337 The proof of concept is more of a demonstration to technology providers on how one can add non-Unicode forms of communication into their product. But we already have examples of this. For example, Slack has support for custom emojis. iPhone has Memojis based on your own avatar. And the flag wouldn't really be the main driver, but rather as a side effect of other reasons why people would want to use some form of higher-abstraction of encoded communication.

**Comment by left4US475** [comment]
@phodamentals stated above in his comment box, "Blood is the symbol of the stripes," is inaccurate or incorrectly interpreted the meaning of the three red stripes. The three red stripes represent the people of the three distinct regions in mind:  North, Central, and South. These people made up Viet Nam. Please take a look at how the term Viet Nam is correctly spelled. The Americans like to combine separate words to make them into one word, and the world didn't know the distinct meaning, thinking it was the correct spelling, so it was adopted, while the scholars of the VNCH didn't want to chime in as they lost their homeland to the VC. Sadly, the VNCH was a vulnerable collective of mass citizens who defied HCM's anti-freedom movement, unempathetic communist governance, and the weasel Lê Duân's starving disrupters whose desire was to make communism strong (their primary objective of creating this unnecessary war that imparted so many dead on land and at sea). I heard that the current CPV allows the natives to voice their concerns about anything (a shrewd Bamboozal policy of a quasi-democracy with no freedom of individual) but jail time to those who criticize their old man HCM (I may have heard wrong), a revere of Mao and Stalin. Amazingly, America thought rebellion was inspirational; unfortunately, a rebellion to take control of others' lives, like the old imperial of Great Britain to the early colonists (immigrants to New America), must not be supported, but it got wild. It can't fight; it joins. I find HCM, Lê Duân, and Võ Văn Giáp were criminals to this unworthy dispute of theirs for what? The country has a corrupted body of government. Pham Minh Chinh has his children running the government, nepotism at best. Children are left unprovided, and education prevents them from understanding the cause of war against the righteousness of individual freedom. People with low incomes have no social support, so they live in the ghetto while the rich live in their comfortable living style; you call that prosperity to the nation? The nation needs to stop diverting foreign investments to feed its fatty belly like that of Pham Minh Chinh and spend on social welfare for the people, which I call a nation that takes care of its people. The CPV must take responsibility for its people instead of begging the U.S.

**Comment by brandonvu99** [comment]
no
