### ISSUE TITLE
Flag of California emoji

### ISSUE THREAD

**Issue by calnation** [Crissov/unicode-proposals#405]
As an authority on emoji proposals, I'd appreciate your help in having California flag added as an emoji. I don't know if there's any pending proposal but in case there isn't then I'd certainly like your help in navigating the process given the variety of alternatives for requesting sub-regional flags as per #358.

Looking forward to hear from you. Thanks in advance  :thumbsup:

**Comment by Crissov** [comment]
As a subdivision (_state_) of a geographical entity recognized in ISO 3166-1, California has a code in ISO 3166-2: `US-CA`. [Unicode flag emojis](http://unicode.org/reports/tr51/) are build upon the [codes](http://www.unicode.org/cldr/charts/latest/supplemental/territory_subdivisions.html) from this standard in two different ways. Pretty much everything I wrote about Catalonia #330 applies. That means the code already exists: 🏴󠁵󠁳󠁣󠁡󠁿 U+1F3F4+E0075+E0073+E0063+E0061+E007F (HTML: `&#x1F3F4;&#xE0075;&#xE0073;&#xE0063;&#xE0061;&#xE007F;`). (@randomguy32 provides a handy [generator](http://randomguy32.de/unicode/tools/iso-3166-2-flag-maker/) for these.) The thing missing is either support from major vendors (Apple, Google, Facebook, Twitter, Samsung &ndash; Microsoft does not support flag emojis at all) or endorsement by the Unicode Emoji Subcommittee. The latter requires a formal proposal and a very, very bad one has been submitted (and, surprisingly, published) before as part of a larger collection in [L2/17-382](http://www.unicode.org/L2/L2017/17382-rgi-flag-omnibus.pdf). This should have been discussed at [UTC 153](http://www.unicode.org/L2/L2017/17361.htm) in October 153, but apparently nothing of it was not advanced further and the [conference minutes](http://www.unicode.org/L2/L2017/17362.htm) are silent on this except for an [indirect note](http://www.unicode.org/L2/L2017/17362.htm#153-A115) on the Basque flag. The issue was not put on the agenda for UTC 154 held in January 2018. I assume the UTC/ESC is waiting for vendors to implement this. There are active efforts for improved flag support at the open-source projects Noto (Google) and Twemoji (Twitter), but they have not made it into the main products yet.

In conclusion, a well-formed proposal for either the flag of California or the flags of all 50 states of the US would not harm, but in this particular case the better course of action would perhaps be to *lobby vendors* to support additional flags, e.g. through petitions. They are reluctant to do so for several reasons, mostly political and UI issues: If they add one state flag they would have to add all of them (although WhatsApp has long gotten away with just shipping the flag of Texas) and it is already a nightmare to find the correct one out of 200ish flags. Most US state flags are also ugly and hard to distinguish (blue banner with coat of arms) especially at small sizes. You would need to address these problems. Still:

- The likely response you will get from vendors is that Unicode does not recommend more flags than they already support and they will add any flag emoji that Unicode does recommend. (_prescriptive_)
- The likely response you will get from Unicode  is that they are waiting to see which additional flags vendors choose to support before they will make them recommended for general interchange (RGI). (_descriptive_)

It's an arguably intensional stalemate between these parties, deflecting the blame.
